### ISSUE TITLE
🚀 Feature: Replace cross-fetch with fetch

### ISSUE THREAD

**Issue by timoo-006** [appwrite/sdk-for-web#82] opened 2023-12-09 19:43 UTC
### 🔖 Feature description

Replace the cross-fetch library with the native browser fetch Implementation

### 🎤 Pitch

I want to call a cloud Function using the SDK in a chrome extension service worker. However chrome extension service workers *do not* support XHR Requests, only the native fetch API

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment] 2024-03-30 17:30
We're working on a fix here: https://github.com/appwrite/sdk-generator/pull/799

**Comment by stnguyen90** [comment] 2024-05-14 20:10
Closing as a duplicate of https://github.com/appwrite/sdk-for-web/issues/53

**Closed by stnguyen90** 2024-05-14 20:10 UTC
Labels: enhancement
