### ISSUE TITLE
🚀 Enhancement: Custom type for OAuth2Provider instead of string

### ISSUE THREAD

**Issue by probablyArth** [appwrite/sdk-for-web#51] opened 2023-03-30 10:06 UTC
### 🔖 Feature description

![image](https://user-images.githubusercontent.com/61962871/228801626-d3e4efae-a816-487a-9710-d4aba6b86b92.png)
Custom type for OAuth2Provider instead of string like the one used here in appwrite-react
https://github.com/sanny-io/react-appwrite/blob/main/src/account/types.ts

```typescript
export type OAuth2Provider =
  | 'amazon'
  | 'apple'
  | 'auth0'
  | 'authentik'
  | 'autodesk'
  | 'bitbucket'
  | 'bitly'
  | 'box'
  | 'dailymotion'
  | 'discord'
  | 'disqus'
  | 'dropbox'
  | 'etsy'
  | 'facebook'
  | 'github'
  | 'gitlab'
  | 'google'
  | 'linkedin'
  | 'microsoft'
  | 'notion'
  | 'okta'
  | 'paypal'
  | 'paypalSandbox'
  | 'podio'
  | 'salesforce'
  | 'slack'
  | 'spotify'
  | 'stripe'
  | 'tradeshift'
  | 'tradeshiftBox'
  | 'twitch'
  | 'wordpress'
  | 'yahoo'
  | 'yammer'
  | 'yandex'
  | 'zoom'
  ```

### 🎤 Pitch

It can provide better developer experience.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment] 2023-03-30 19:11
Hi, thank you for the suggestion.
This might be a bit difficult since we use the SDK generator for everything. However, your idea is appreciated and I will keep this issue open for now in case there are others from the community interested in discussing this.

**Comment by stnguyen90** [comment] 2023-04-07 13:54
@probablyArth this looks like a duplicate of <https://github.com/appwrite/appwrite/issues/426>. Can we close this and you can 👍 the other issue?

**Closed** 2023-04-07 14:06 UTC
