### ISSUE TITLE
🐛 Bug Report: We should remove top level `types` field in `package.json`.

### ISSUE THREAD

**Issue by Lalit3716** [appwrite/sdk-for-web#55] opened 2023-05-20 14:21 UTC
### 👟 Reproduction steps

1) Initialize a TypeScript project with `moduleResolution: "bundler"` in your `tsconfig`.
2) Install `appwrite` web sdk.
3) Try to import it you will see that for the sdk, types will be undefined.

This is due to the fact that for TypeScript to work with packages that have `exports` field when using the new `moduleResolution: node16/nodenext/bundler` settings. When those are not used then TypeScript just ignores `package.json#exports` - but when you make it aware of `exports` by using those options then it requires the types to be included in `exports` and not as the top-level key of `package.json`.

You can also visit this tool to check that the types for this sdk are definitely wrong: https://arethetypeswrong.github.io/.

### 👍 Expected behavior

Types should be well defined.

### 👎 Actual Behavior

Types aren't well defined with ` moduleResolution: "bundler"` option on in your `tsconfig.json`.

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Lalit3716** [comment] 2023-05-20 14:22
I found this issue when working on something for the ongoing appwrite hackathon 😅 and I know how to fix it as well but I am not sure where to open the PR since this is a READ ONLY repository.

**Comment by justin-prather** [comment] 2023-05-21 20:25
@Lalit3716 do you have a way to patch this for the time being? running into this issue as well and id love  work around

**Comment by Lalit3716** [comment] 2023-05-22 00:45
Yeah for the time being I manually edit `node_modules/appwrite/package.json` to remove `exports` field.

**Comment by stnguyen90** [comment] 2023-05-23 05:19
Closing as a duplicate of https://github.com/appwrite/sdk-for-web/issues/54

**Closed by stnguyen90** 2023-05-23 05:19 UTC
Labels: bug
